### ISSUE TITLE
Questions for SW

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/ghg-processor#1]
Files

- [x] The easiest way to break the script will be if someone changes the metadata file

Times and such

- [x] "Time_start" in the metadata file will always be in INSTRUMENT TIME, right?

Concentration data

- [x] 5% of the CO2 concentrations in the test file are (quite) negative. How do you want to handle? If omit, should the corresponding CH4 observations be dropped as well?
- [x] What about seeming multiple observations with a single 5-minute period?

Science

- [x] Why are you doing five minute observations? Seems very long

**Comment by wilsonsj100** [comment]
Hi Ben, 

Files: 
Yes, that is what I was doing before. If I noticed that the flux started a bit later than what was written down or if there seemed to be something weird I would change the metadata and note it. 

Times and such
Yes, the metadata file will always been in instrument time, but we decided we should also be writing the time difference between the licor and real time so later we can pull other environmental data from the same time frame. 

Concentration data 
Does the negative data come up before the flux or during? because if it seems to be at the beginning I think it is probably an artifact of getting the flux set up? When I look at the code I only see a few at the beginning of flux 2 that look really negative - is that correct? I would think we would want to take those points out and start the flux later. I will ask Pat, but I would think that would only occur if there was a pressure artifact or something - maybe the Licor sitting on the tubing on the boardwalk and preventing flow as we are getting set up? 
Seeing multiple observations within a single five minute period likely means someone started a flux then realized something was wrong and restarted. Let's retry with the new meta-data files since I saw that there was a flux that was redone in June that needed adjusted (note was on the side of the scanned field doc and not super noticeable). 

Science 
This seems to be the standard in our lab across all of our chamber measuring projects.

**Comment by bpbond** [comment]
Oh! I see, that 5% number was from _everything_, including when the machine wasn't measuring a collar. OK, that makes sense. The relevant values are when measuring. Sorry, not used to continuously-running machine data.

Now:
```
Observations with negative CO2: 3 (0%)

Observations with missing CO2: 397 (26%)

Observations with missing CH4: 397 (26%)
```
![unnamed-chunk-8-1](https://user-images.githubusercontent.com/1956468/211698200-495f282a-1708-4b94-b8b1-b4b32f17889f.png)

**Comment by bpbond** [comment]
The new metadata file still has some, um, issues 😄 

![unnamed-chunk-11-1](https://user-images.githubusercontent.com/1956468/211699379-dad62616-e6e5-41ef-8a9a-9460c09d995d.png)

We can automatically add some initial dead band time, that's fine, but chambers 3-5 above clearly have multiple measurements in them, and the start time for 2 seems completely off. Does that look right to you?

**Comment by wilsonsj100** [comment]
Hey Ben, 

I think something is off.... when I run the code on my computer I get this for the fluxes..... 

![image](https://user-images.githubusercontent.com/122289915/211700549-b51997ff-ae69-421f-8c9a-7ba761a0b282.png)

CH4: 
![image](https://user-images.githubusercontent.com/122289915/211700571-d8a7b7f5-30e7-4925-a3c8-c568d89bc368.png)

CO2: 
![image](https://user-images.githubusercontent.com/122289915/211700587-c5b11f37-8b70-4194-b730-5031838f2c50.png)

Something is fishy... happy to zoom later this week.

**Comment by bpbond** [comment]
Yep, a bug. F***ing time zones. Sorry, all good now.

![unnamed-chunk-10-1](https://user-images.githubusercontent.com/1956468/211704441-1e441515-e917-4fe5-ae88-66b5bbc1b587.png)

![unnamed-chunk-11-1](https://user-images.githubusercontent.com/1956468/211704465-11421ce0-d05e-4155-a881-fcfc2505d365.png)

![unnamed-chunk-11-2](https://user-images.githubusercontent.com/1956468/211704494-b0b1dc39-bdf4-47f1-a74b-d83c87ca83d1.png)

**Comment by wilsonsj100** [comment]
WooHoo! At least it was a fixable problem :) Thank you!
